version: 2.1

commands:
  destroy-environment:
    description: Destroy environments  
    steps:
      - run:
          name: Destroy environments
          when: on_fail
          command: |
            terraform destroy


jobs:
  build:
    docker:
      # Use the same Docker base as the project 
      - image: python:3.7.3-stretch

    working_directory: ~/repo

    steps:
      - checkout

      # Download and cache dependencies
      - restore_cache:
          keys:
            - v1-dependencies-{{ checksum "requirements.txt" }}
            # fallback to using the latest cache if no exact match is found
            - v1-dependencies-

      - run:
          name: install dependencies
          command: |
            python3 -m venv venv
            . venv/bin/activate
            make install
            pip install pylint
            # Install hadolint
            wget -O /bin/hadolint https://github.com/hadolint/hadolint/releases/download/v1.16.3/hadolint-Linux-x86_64 &&\
            chmod +x /bin/hadolint
      - save_cache:
          paths:
            - ./venv
          key: v1-dependencies-{{ checksum "requirements.txt" }}

  # run lint!
      - run:
          name: run lint
          command: |
            . venv/bin/activate
            make lint 
  
  create-infrastructure:
    docker: 
      - image: amazon/aws-cli
    steps:
      - checkout
      - run:
          name: Install tar gzip and awscli
          command: |
            yum install -y tar gzip
      - run:
          name: Install terraform
          command: |
            yum install -y yum-utils
            yum-config-manager --add-repo https://rpm.releases.hashicorp.com/AmazonLinux/hashicorp.repo
            yum -y install terraform
      - run:
          name: Deploy infrastructure
          command: |
            cd infrastructure/
            terraform init
            terraform plan
            terraform -auto-approve apply
            cd ..
      - run:
          name: Add server ip to ansible inventory
          command: |
            aws ec2 describe-instances \
              --query 'Reservations[*].Instances[*].PublicIpAddress' \
              --filters "Name=tag:project,Values=Menu_app" \
              --output text >> .circleci/ansible/inventory.txt
            cat .circleci/ansible/inventory.txt
      - persist_to_workspace:
          root: ~/
          paths:
            - project/.circleci/ansible/inventory.txt
      - destroy-environment

  configure-infrastructure:
    docker:
      - image: python:3.7-alpine3.11
    steps:
      - checkout
      - add_ssh_keys:
            fingerprints: ["22:e4:5c:56:26:31:a9:63:51:10:71:c2:60:3c:c5:02"] 
      - attach_workspace:
          at: ~/
      - run:
          name: Install dependencies
          command: |
            apk add --update ansible
            apk add --update tar gzip
      - run:
          name: Configure server
          command: |
            cd .circleci/ansible
            ansible-playbook -i inventory.txt config-server.yml 
      - destroy-environment
  
  deploy-app:
    docker:
      - image: amazon/aws-cli
    steps:
      - checkout
      - run:
          name: Install terraform
          command: |
            yum install -y yum-utils
            yum-config-manager --add-repo https://rpm.releases.hashicorp.com/AmazonLinux/hashicorp.repo
            yum -y install terraform
      - run:
          name: Build and run docker image
          command: |
            ./run_docker.sh
      - destroy-environment

workflows:
  default:
    jobs:
      - build
      - create-infrastructure:
          requires: [build]
      - configure-infrastructure:
          requires: [create-infrastructure]
      - deploy-app:
          requires: [configure-infrastructure]
        


